language: java

os: osx

osx_image: xcode9.2

before_install:
  - brew update
  - brew outdated xctool || brew upgrade xctool
  - npm install -g appium
  - xcrun simctl list -j devices

script: Platform="ios" mvn clean -Dtest=Runner test
